"""Add owner_name and other new columns to properties table

Revision ID: 6f7fda7bd1ce
Revises: 
Create Date: 2025-04-21 17:43:02.241028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7fda7bd1ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('type')
        batch_op.drop_column('location')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
