"""Add additional_assessment and outcome to Audit

Revision ID: ab759c77bca9
Revises: d9f322aac228
Create Date: 2025-04-22 15:09:06.397833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab759c77bca9'
down_revision = 'd9f322aac228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_assessment', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('outcome')
        batch_op.drop_column('additional_assessment')

    # ### end Alembic commands ###
