"""Add flagging fields to TaxReturn

Revision ID: d3f6c8cd8758
Revises: ab759c77bca9
Create Date: 2025-05-06 08:29:28.109079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f6c8cd8758'
down_revision = 'ab759c77bca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_reason', sa.Text(), nullable=True))
    # Set default value False for all existing rows
    op.execute("UPDATE tax_returns SET is_flagged = FALSE WHERE is_flagged IS NULL;")
    # Alter column to be non-nullable
    with op.batch_alter_table('tax_returns', schema=None) as batch_op:
        batch_op.alter_column('is_flagged', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_returns', schema=None) as batch_op:
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
